function ch_bfh_red_app_widgetset_RedappWidgetset(){var Z='',W=' top: -1000px;',ub='" for "gwt:onLoadErrorFn"',sb='" for "gwt:onPropertyErrorFn"',db='");',vb='#',ac='.cache.js',xb='/',Db='//',Vb='10275A7407A8E3C4A79CA9ED4A7E2112',Wb='4251A972359AE6EA8A21D94E69684900',Xb='5A0FCC6D77E867F9E04DA00E197C9FB5',_b=':',Zb=':1',mb='::',lc=':moduleBase',Y='<!doctype html>',$='<html><head><\/head><body><\/body><\/html>',pb='=',wb='?',rb='Bad handler "',X='CSS1Compat',bb='Chrome',ab='DOMContentLoaded',R='DUMMY',Yb='E06BA9D7B6EBBA6A466C5E3CFDE6EFC4',$b='FD143550B8838B32420E66D09561FD3A',kc='__gwtDevModeHook:ch.bfh.red.app.widgetset.RedappWidgetset',Qb='android 2.',Rb='android2',Cb='base',Ab='baseUrl',M='begin',S='body',L='bootstrap',P='ch.bfh.red.app.widgetset.RedappWidgetset',Ub='ch.bfh.red.app.widgetset.RedappWidgetset.devmode.js',Bb='ch.bfh.red.app.widgetset.RedappWidgetset.nocache.js',lb='ch.bfh.red.app.widgetset.RedappWidgetset::',zb='clear.cache.gif',gc='com_vaadin_addon_timeline/styles.css',ob='content',hc='end',cb='eval("',jc='file:',Mb='gecko',Nb='gecko1_8',N='gwt.codesvr.ch.bfh.red.app.widgetset.RedappWidgetset=',O='gwt.codesvr=',tb='gwt:onLoadErrorFn',qb='gwt:onPropertyErrorFn',nb='gwt:property',ib='head',ec='href',ic='http:',Lb='ie6',Kb='ie8',Jb='ie9',T='iframe',yb='img',fb='javascript',U='javascript:""',bc='link',fc='loadExternalRefs',jb='meta',hb='moduleRequested',gb='moduleStartup',Ib='msie',kb='name',Fb='opera',V='position:absolute; width:0; height:0; border:none; left: -1000px;',cc='rel',Hb='safari',eb='script',Tb='selectingPermutation',Q='startup',Sb='std',dc='stylesheet',_='undefined',Ob='unknown',Eb='user.agent',Gb='webkit',Pb='webkitvariant';var o=window;var p=document;r(L,M);function q(){var a=o.location.search;return a.indexOf(N)!=-1||a.indexOf(O)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:P,sessionId:o.__gwtStatsSessionId,subSystem:Q,evtGroup:a,millis:(new Date).getTime(),type:b})}}
ch_bfh_red_app_widgetset_RedappWidgetset.__sendStats=r;ch_bfh_red_app_widgetset_RedappWidgetset.__moduleName=P;ch_bfh_red_app_widgetset_RedappWidgetset.__errFn=null;ch_bfh_red_app_widgetset_RedappWidgetset.__moduleBase=R;ch_bfh_red_app_widgetset_RedappWidgetset.__softPermutationId=0;ch_bfh_red_app_widgetset_RedappWidgetset.__computePropValue=null;ch_bfh_red_app_widgetset_RedappWidgetset.__getPropMap=null;ch_bfh_red_app_widgetset_RedappWidgetset.__gwtInstallCode=function(){};ch_bfh_red_app_widgetset_RedappWidgetset.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[P]={moduleName:P};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(S)[0]}
function y(){if(v){return}var a=p.createElement(T);a.src=U;a.id=P;a.style.cssText=V+W;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==X?Y:Z;v.write(b+$);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==_){return typeof p.body!=_&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(ab,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(ab,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(bb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(cb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(db));g=f.createElement(eb);g.language=fb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(eb);g.language=fb;g.text=c[i];e.appendChild(g);d(e,g)}}}
ch_bfh_red_app_widgetset_RedappWidgetset.onScriptDownloaded=function(a){l(function(){m(a)})};r(gb,hb);var n=p.createElement(eb);n.src=k;p.getElementsByTagName(ib)[0].appendChild(n)}
ch_bfh_red_app_widgetset_RedappWidgetset.__startLoadingFragment=function(a){return C(a)};ch_bfh_red_app_widgetset_RedappWidgetset.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(eb);c.language=fb;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(jb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(kb),k;if(j){j=j.replace(lb,Z);if(j.indexOf(mb)>=0){continue}if(j==nb){k=i.getAttribute(ob);if(k){var l,m=k.indexOf(pb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Z}c[j]=l}}else if(j==qb){k=i.getAttribute(ob);if(k){try{d=eval(k)}catch(a){alert(rb+k+sb)}}}else if(j==tb){k=i.getAttribute(ob);if(k){try{e=eval(k)}catch(a){alert(rb+k+ub)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;ch_bfh_red_app_widgetset_RedappWidgetset.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(vb);if(b==-1){b=a.length}var c=a.indexOf(wb);if(c==-1){c=a.length}var d=a.lastIndexOf(xb,Math.min(c,b));return d>=0?a.substring(0,d+1):Z}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(yb);b.src=a+zb;a=e(b.src)}return a}
function g(){var a=t(Ab);if(a!=null){return a}return Z}
function h(){var a=p.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Bb)!=-1){return e(a[b].src)}}return Z}
function i(){var a=p.getElementsByTagName(Cb);if(a.length>0){return a[a.length-1].href}return Z}
function j(){var a=p.location;return a.href==a.protocol+Db+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Z){k=h()}if(k==Z){k=i()}if(k==Z&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return ch_bfh_red_app_widgetset_RedappWidgetset.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Eb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Fb)!=-1}())return Fb;if(function(){return b.indexOf(Gb)!=-1}())return Hb;if(function(){return b.indexOf(Ib)!=-1&&p.documentMode>=9}())return Jb;if(function(){return b.indexOf(Ib)!=-1&&p.documentMode>=8}())return Kb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Lb;if(function(){return b.indexOf(Mb)!=-1}())return Nb;return Ob};i[Eb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};j[Pb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Qb)!=-1){return Rb}return Sb}};i[Pb]={android2:0,std:1};s=function(a,b){return b in i[a]};ch_bfh_red_app_widgetset_RedappWidgetset.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};ch_bfh_red_app_widgetset_RedappWidgetset.__computePropValue=k;o.__gwt_activeModules[P].bindings=ch_bfh_red_app_widgetset_RedappWidgetset.__getPropMap;r(L,Tb);if(q()){return C(Ub)}var l;try{h([Kb,Sb],Vb);h([Fb,Sb],Wb);h([Nb,Sb],Xb);h([Hb,Rb],Yb);h([Hb,Sb],Yb+Zb);h([Jb,Sb],$b);l=f[k(Eb)][k(Pb)];var m=l.indexOf(_b);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}ch_bfh_red_app_widgetset_RedappWidgetset.__softPermutationId=g;return C(l+ac)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(bc);b.setAttribute(cc,dc);b.setAttribute(ec,C(a));p.getElementsByTagName(ib)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(fc,M);c(gc);r(fc,hc)}
A();ch_bfh_red_app_widgetset_RedappWidgetset.__moduleBase=B();u[P].moduleBase=ch_bfh_red_app_widgetset_RedappWidgetset.__moduleBase;var F=D();if(o){var G=!!(o.location.protocol==ic||o.location.protocol==jc);o.__gwt_activeModules[P].canRedirect=G;if(G){var H=kc;var I=o.sessionStorage[H];if(I&&!o[H]){o[H]=true;o[H+lc]=B();var J=p.createElement(eb);J.src=I;var K=p.getElementsByTagName(ib)[0];K.insertBefore(J,K.firstElementChild||K.children[0]);return false}}}E();r(L,hc);z(F);return true}
ch_bfh_red_app_widgetset_RedappWidgetset.succeeded=ch_bfh_red_app_widgetset_RedappWidgetset();