package ch.bfh.red.app.controller;

import java.io.Serializable;
import java.lang.reflect.Method;
import java.util.Calendar;

import ch.bfh.red.app.model.assignment.Diary;
import ch.bfh.red.app.model.assignment.Diary.FeelingEnum;
import ch.bfh.red.app.view.DiarySummaryView;
import ch.bfh.red.app.view.RedAppUI;

import com.vaadin.addon.jpacontainer.JPAContainer;
import com.vaadin.addon.jpacontainer.JPAContainerFactory;
import com.vaadin.addon.touchkit.ui.NavigationView;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Component;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Upload;

public class DiaryEditor extends NavigationView implements ClickListener {

	private Button cancel;
	private Button submit;

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label lbFoto;
	@AutoGenerated
	private Upload upload;
	@AutoGenerated
	private TextArea taEntry;
	@AutoGenerated
	private Label lbEntry;
	@AutoGenerated
	private OptionGroup ogFeel;
	@AutoGenerated
	private Label lbFeel;
	private Item diaryItem;
	FieldGroup binder;

	private JPAContainer<Diary> diaries;

	public DiaryEditor(final Item diaryItem) {

		this.diaryItem = diaryItem;
	}

	@Override
	public void attach() {
		super.attach();
		buildView();
	}

	private void buildView() {
		cancel = new Button(null, this);
		cancel.setCaption("Cancel");

		getNavigationBar().setLeftComponent(cancel);

		submit = new Button(null, this);
		submit.setCaption("Save");
		getNavigationBar().setRightComponent(submit);

		setPreviousComponent(new DiarySummaryView());
		this.diaries = JPAContainerFactory.make(Diary.class, RedAppUI.PERSISTENCE_UNIT);

		this.addListener(new EditorSavedListener() {
			private static final long serialVersionUID = -4810596568407523252L;

			@Override
			public void editorSaved(EditorSavedEvent event) {
				// get and set current DateTime
				BeanItem<Diary> newDiaryItem = (BeanItem<Diary>) diaryItem;
				newDiaryItem.getBean().setDateTime(Calendar.getInstance());

				diaries.addEntity(newDiaryItem.getBean());

			}
		});

		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();

		// lbFeel
		lbFeel = new Label();
		lbFeel.setImmediate(false);
		lbFeel.setWidth("-1px");
		lbFeel.setHeight("-1px");
		lbFeel.setValue("Wie fühlst du dich heute?");
		mainLayout.addComponent(lbFeel, "top:60.0px;left:80.0px;");

		// ogFeel
		ogFeel = new OptionGroup();
		ogFeel.setImmediate(false);
		ogFeel.setWidth("100.0%");
		ogFeel.setHeight("80px");

		for (FeelingEnum fe : Diary.FeelingEnum.values()) {
			ogFeel.addItem(fe);
		}

		mainLayout.addComponent(ogFeel, "top:80.0px;left:80.0px;");

		// lbEntry
		lbEntry = new Label();
		lbEntry.setImmediate(false);
		lbEntry.setWidth("-1px");
		lbEntry.setHeight("-1px");
		lbEntry.setValue("Tagebucheintrag:");
		mainLayout.addComponent(lbEntry, "top:180.0px;left:80.0px;");

		// taEntry
		taEntry = new TextArea();
		taEntry.setImmediate(false);
		taEntry.setWidth("340px");
		taEntry.setHeight("156px");

		mainLayout.addComponent(taEntry, "top:200.0px;left:80.0px;");

		// submit
		// mainLayout.addComponent(submit, "top:480.0px;left:357.0px;");

		// cancel
		// mainLayout.addComponent(cancel, "top:480.0px;left:120.0px;");

		binder = new FieldGroup(diaryItem);

		binder.bind(taEntry, "entry");
		binder.bind(ogFeel, "feeling");

		taEntry.setValue("Liebes Tagebuch.... ");

		setContent(mainLayout);

	}

	public void buttonClick(ClickEvent event) {

		if (event.getButton() == submit) {
			try {
				binder.commit();
			} catch (CommitException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			fireEvent(new EditorSavedEvent(this, diaryItem));
		} else if (event.getButton() == cancel) {
			binder.discard();
		}
		getNavigationManager().navigateBack();

	}

	public void addListener(EditorSavedListener listener) {
		try {
			Method method = EditorSavedListener.class.getDeclaredMethod("editorSaved", new Class[] { EditorSavedEvent.class });
			addListener(EditorSavedEvent.class, listener, method);
		} catch (final java.lang.NoSuchMethodException e) {
			// This should never happen
			throw new java.lang.RuntimeException("Internal error, editor saved method not found");
		}
	}

	public void removeListener(EditorSavedListener listener) {
		removeListener(EditorSavedEvent.class, listener);
	}

	public static class EditorSavedEvent extends Component.Event {

		private Item savedItem;

		public EditorSavedEvent(Component source, Item savedItem) {
			super(source);
			this.savedItem = savedItem;
		}

		public Item getSavedItem() {
			return savedItem;
		}
	}

	public interface EditorSavedListener extends Serializable {
		public void editorSaved(EditorSavedEvent event);
	}
}